# -*- coding: utf-8 -*-
"""transformers_7_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iVc3vxJP6dUIs9PgHULTMQqcJnQFxO4
"""

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import TrainingArguments, Trainer

import torch
                                
print("CUDA available:", torch.cuda.is_available())                                    #returns a flag
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")   #returns name

!pip install -q transformers datasets accelerate evaluate

import pandas as pd

df = pd.read_csv("cleaned_spam.csv")

print(df.shape)
print(df.head())
print(df.columns)

from sklearn.model_selection import train_test_split

X = df["clean_message"]
y = df["label"]

# Convert labels to numbers
y = y.map({
    "ham": 0,
    "spam": 1
})

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Test samples:", len(X_test))

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(    #automatically select the correct tokenizer configuration
    "distilbert-base-uncased"                 #distilled version of bert having base size architecture and doesn't have any distinction between upper and lower case letters (uncased)
)

text = "Congratulations! You won a free prize."

tokens = tokenizer(text)

print(tokens)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

from datasets import Dataset

train_df = pd.DataFrame({
    "text": X_train.values,
    "label": y_train.values
})

test_df = pd.DataFrame({
    "text": X_test.values,
    "label": y_test.values
})

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

print(train_dataset)
print(test_dataset)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        padding="max_length", #each sequence is padded to the maximum length of 128 tokens, ensuring uniform input size for the model
        truncation=True,      #strip off any tokens that exceed the maximum length of 128 tokens, preventing errors during model training and evaluation
        max_length=128       
    )

train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True
)

test_tokenized = test_dataset.map(
    tokenize_function,
    batched=True
)

train_tokenized = train_tokenized.remove_columns(["text"])
test_tokenized = test_tokenized.remove_columns(["text"])

train_tokenized.set_format("torch")
test_tokenized.set_format("torch")

"""Load DistilBERT"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = logits.argmax(axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary",
        zero_division=0
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

training_args = TrainingArguments(
    output_dir="./bert_results",
    num_train_epochs=3,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,
    compute_metrics=compute_metrics
)

import datasets.config as _dsconfig
_dsconfig.TORCHVISION_AVAILABLE = False

"""## Train the model"""

train_result = trainer.train()
print(train_result)

"""## Final evaluation on the held-out test set

`compute_metrics` above only reports overall accuracy/precision/recall/F1 (binary average). To match the per-class report format used for TF-IDF and LSTM (`classification_report` with `target_names=["ham","spam"]`), we run predictions directly and build the same report.
"""

from sklearn.metrics import classification_report
import numpy as np

# Get raw model predictions (logits) on the test set
predictions_output = trainer.predict(test_tokenized)

# Convert logits to predicted class (0 = ham, 1 = spam)
y_pred_bert = np.argmax(predictions_output.predictions, axis=-1)
y_true_bert = predictions_output.label_ids

print("BERT (DistilBERT) Test Set Evaluation")
print("=" * 50)
print(classification_report(
    y_true_bert,
    y_pred_bert,
    target_names=["ham", "spam"],
    zero_division=0
))

"""## Save the fine-tuned model and tokenizer"""

import os

save_dir = "models/distilbert_spam"
os.makedirs(save_dir, exist_ok=True)

trainer.save_model(save_dir)
tokenizer.save_pretrained(save_dir)

print(f"Model and tokenizer saved to {save_dir}")

"""## Build the comparison row for the final table

Matches the `Model, Accuracy, Spam Precision, Spam Recall, Spam F1` format used in the TF-IDF/GloVe and LSTM result CSVs so this can be merged into the final three-way comparison table.
"""

import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

bert_accuracy = accuracy_score(y_true_bert, y_pred_bert)
bert_precision, bert_recall, bert_f1, _ = precision_recall_fscore_support(
    y_true_bert,
    y_pred_bert,
    average="binary",
    pos_label=1,
    zero_division=0
)

bert_results = pd.DataFrame({
    "Model": ["DistilBERT (fine-tuned)"],
    "Accuracy": [bert_accuracy],
    "Spam Precision": [bert_precision],
    "Spam Recall": [bert_recall],
    "Spam F1": [bert_f1]
})

os.makedirs("results", exist_ok=True)
bert_results.to_csv("results/bert_results.csv", index=False)

print(bert_results.to_string(index=False, float_format=lambda x: f"{x:.4f}"))
print("\nSaved to results/bert_results.csv")

"""## Misclassified examples (Required Analysis Q5)

Pulls a few test messages the model got wrong, for the "where does your best model fail" writeup.
"""

wrong_idx = np.where(y_pred_bert != y_true_bert)[0]

print(f"Total misclassified: {len(wrong_idx)} out of {len(y_true_bert)}")
print("=" * 70)

sample_wrong = wrong_idx[:5]
for i in sample_wrong:
    true_label = "spam" if y_true_bert[i] == 1 else "ham"
    pred_label = "spam" if y_pred_bert[i] == 1 else "ham"
    message_text = test_df.iloc[i]["text"]
    print(f"True: {true_label:5s} | Predicted: {pred_label:5s}")
    print(f"Message: {message_text}")
    print("-" * 70)